apache/paimon-webui

paimon-web-ui/package.json
paimon-web-ui/src/components/Editor/index.tsx
paimon-web-ui/src/pages/Playground/RightContent/TopPanel/Tab/index.tsx

change MonacoEditor version , use MonacoEditor official

[Optimize][Web]change MonacoEditor version

---

paimon-web-server/pom.xml
paimon-web-server/src/main/resources/application-dev.yml
paimon-web-server/src/main/resources/db/ddl-h2.sql
paimon-web-server/src/main/resources/db/dml-h2.sql

[Feature][web]add h2

---

paimon-web-ui/package.json
paimon-web-ui/src/components/ChangeI18nBtn/index.tsx
paimon-web-ui/src/components/Dropdown/CatalogDropdown.tsx
paimon-web-ui/src/components/Search/index.tsx
paimon-web-ui/src/config/menu.tsx
paimon-web-ui/src/locales/en/translation.json
paimon-web-ui/src/locales/i18n.ts
paimon-web-ui/src/locales/zh-CN/translation.json
paimon-web-ui/src/main.tsx
paimon-web-ui/src/pages/Layout/Header/index.tsx
paimon-web-ui/src/pages/Metadata/components/LeftContent/components/CatalogTree/index.tsx
paimon-web-ui/src/pages/Metadata/components/LeftContent/index.tsx
paimon-web-ui/src/pages/Metadata/components/RightContent/components/MainContent/Table/index.tsx
paimon-web-ui/src/pages/Playground/components/TabMenuSidebar/components/TreeComponent/index.tsx

[Feature][UI]support i18n

---

paimon-web-api/pom.xml
paimon-web-server/pom.xml
paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/LoginController.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/data/result/enums/Status.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/data/result/exception/user/UserNotBindTenantException.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/data/vo/UserInfoVo.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/RoleMenuService.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/SysMenuService.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/TenantService.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/UserRoleService.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/UserService.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/UserTenantService.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/RoleMenuServiceImpl.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/TenantServiceImpl.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/UserRoleServiceImpl.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/UserServiceImpl.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/UserTenantServiceImpl.java
paimon-web-server/src/main/resources/application-prod.yml
paimon-web-server/src/main/resources/application.yml
paimon-web-server/src/main/resources/i18n/messages.properties
paimon-web-server/src/main/resources/i18n/messages_en_US.properties
paimon-web-server/src/main/resources/i18n/messages_zh_CN.properties
paimon-web-ui/package.json
paimon-web-ui/src/api/endpoints.ts
paimon-web-ui/src/api/http.ts
paimon-web-ui/src/pages/Other/Login/index.tsx
paimon-web-ui/src/router/index.tsx
paimon-web-ui/src/types/Public/data.d.ts
paimon-web-ui/src/types/User/data.d.ts
pom.xml

[Feature] Added Login Page

---

paimon-web-ui-new/auto-imports.d.ts
paimon-web-ui-new/src/composables/locales.ts
paimon-web-ui-new/src/layouts/content/components/menubar/index.tsx
paimon-web-ui-new/src/layouts/content/components/toolbar/index.tsx
paimon-web-ui-new/src/locales/index.ts
paimon-web-ui-new/src/store/config/index.ts
paimon-web-ui-new/src/views/login/index.tsx
paimon-web-ui-new/src/views/login/use-form.ts
paimon-web-ui-new/tsconfig.app.json
paimon-web-ui-new/vite.config.ts

language hooks encapsulation
configuration composables and api autoImport

[Feature] language hooks encapsulation & auto import configuration

---

paimon-web-ui-new/src/components/context-menu/index.module.scss
paimon-web-ui-new/src/components/context-menu/index.tsx
paimon-web-ui-new/src/locales/en/modules/playground.ts
paimon-web-ui-new/src/views/playground/components/query/components/tabs/index.tsx
paimon-web-ui-new/src/views/playground/components/workbench/components/menu-tree/index.tsx
paimon-web-ui-new/src/views/playground/components/workbench/components/tabs/index.tsx

Please refer to the main `issue`  [#44](https://github.com/apache/incubator-paimon-webui/issues/44)

[Feature] add context menu

---

paimon-web-api/pom.xml
pom.xml

[Feature] Bump the snapshot version of Paimon to 0.6-SNAPSHOT

---

paimon-web-ui-new/src/views/metadata/components/metadata-tabs/index.tsx
paimon-web-ui-new/src/views/metadata/components/table/index.tsx

Enhance metadata TableInfo module table and pagination

[Feature] Enhance metadata table info module style

---

paimon-web-ui-new/src/locales/en/index.ts
paimon-web-ui-new/src/locales/en/modules/cdc.ts
paimon-web-ui-new/src/locales/zh/index.ts
paimon-web-ui-new/src/locales/zh/modules/cdc.ts
paimon-web-ui-new/src/views/cdc/components/list/index.module.scss
paimon-web-ui-new/src/views/cdc/components/list/index.tsx
paimon-web-ui-new/src/views/cdc/components/table-action/index.tsx
paimon-web-ui-new/src/views/cdc/index.tsx

please refer to  the main `issue` [ #77 ] (https://github.com/apache/incubator-paimon-webui/issues/77)

[Feature] Introduce CDC Ingestion list page

---

paimon-web-ui-new/src/api/models/catalog/index.ts
paimon-web-ui-new/src/api/models/catalog/interface.ts
paimon-web-ui-new/src/api/request.ts
paimon-web-ui-new/src/router/modules/metadata.ts
paimon-web-ui-new/src/store/catalog/index.ts
paimon-web-ui-new/src/views/metadata/components/menu-tree/index.tsx

Metadata get all catalog api fetch & render menu

[Feature] Fetch metadata with getAllCatalogs API

---

paimon-web-ui-new/package.json
paimon-web-ui-new/pnpm-lock.yaml
paimon-web-ui-new/src/locales/zh/modules/cdc.ts
paimon-web-ui-new/src/main.ts
paimon-web-ui-new/src/views/cdc/components/dag/custom-node.tsx
paimon-web-ui-new/src/views/cdc/components/dag/dag-canvas.tsx
paimon-web-ui-new/src/views/cdc/components/dag/dag-slider.tsx
paimon-web-ui-new/src/views/cdc/components/dag/index.module.scss
paimon-web-ui-new/src/views/cdc/components/dag/index.tsx
paimon-web-ui-new/src/views/cdc/components/dag/node-config.ts
paimon-web-ui-new/src/views/cdc/components/dag/use-canvas-init.ts

Please refer to the main `issue`  [#77 ](https://github.com/apache/incubator-paimon-webui/issues/77).

[Feature] Introduce x6 dag component

---

paimon-web-ui-new/src/api/models/catalog/index.ts
paimon-web-ui-new/src/store/catalog/index.ts
paimon-web-ui-new/src/views/metadata/components/menu-tree/index.tsx

MenuTree lazyLoad mock finish & interaction complete
suffix button style finish

[Feature] Enhance metadata menu tree lazy load mock and suffix button style

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/data/dto/QueryMetadataDTO.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/MetadataServiceImpl.java
paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/MetadataControllerTest.java

[Improvement] Query catalog metadata with catalog id

---

paimon-web-ui-new/src/locales/en/modules/job.ts
paimon-web-ui-new/src/locales/zh/index.ts
paimon-web-ui-new/src/locales/zh/modules/job.ts
paimon-web-ui-new/src/router/modules/job.ts
paimon-web-ui-new/src/router/routes.ts
paimon-web-ui-new/src/views/job/components/statistic-card/index.module.scss
paimon-web-ui-new/src/views/job/components/statistic-card/index.tsx
paimon-web-ui-new/src/views/job/components/status-tag/index.tsx
paimon-web-ui-new/src/views/job/constant.ts
paimon-web-ui-new/src/views/job/constant.tsx
paimon-web-ui-new/src/views/job/index.module.scss
paimon-web-ui-new/src/views/job/index.tsx
paimon-web-ui-new/vite.config.ts

redesign & job management style finish

[Feature]: job management style finish

---

paimon-web-ui-new/package.json
paimon-web-ui-new/pnpm-lock.yaml
paimon-web-ui-new/src/api/models/catalog/index.ts
paimon-web-ui-new/src/api/models/catalog/interface.ts
paimon-web-ui-new/src/api/request.ts
paimon-web-ui-new/src/api/types.ts
paimon-web-ui-new/src/store/catalog/index.ts
paimon-web-ui-new/src/views/metadata/components/datafile/index.tsx
paimon-web-ui-new/src/views/metadata/components/manifest/index.tsx
paimon-web-ui-new/src/views/metadata/components/menu-tree/index.tsx
paimon-web-ui-new/src/views/metadata/components/schema/index.tsx
paimon-web-ui-new/src/views/metadata/components/snapshot/index.tsx
paimon-web-ui-new/vite.config.ts

Request refactor.
MetaData
- snapshot
- schema
- manifest
- datafile
api fetch

[Improvement] Refactor fetch request of metadata datafile, snapshot, schema and manifest interface

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/MetadataServiceImpl.java

get files metadata throw class case exception
fix #112

[Bugfix] Fix ClassCaseException for getting files metadata

---

.gitignore
paimon-web-ui-new/.eslintignore
paimon-web-ui-new/README.md
paimon-web-ui-new/mock/mm.config.js
paimon-web-ui-new/mock/modules/index.js
paimon-web-ui-new/mock/modules/metadata.js
paimon-web-ui-new/package.json
paimon-web-ui-new/pnpm-lock.yaml
paimon-web-ui-new/src/api/request.ts
paimon-web-ui-new/vite.config.ts

Integrated mock mode. In order to run the project without back-end service

[Feature] Support integration with mock mode

---

paimon-web-ui-new/README.md
paimon-web-ui-new/mock/mm.config.js
paimon-web-ui-new/mock/modules/index.js
paimon-web-ui-new/mock/modules/metadata.js
paimon-web-ui-new/src/views/metadata/components/schema/index.tsx

Mock Server Docs & Mock Web Server
Metadata mock integrated

[Feature] Support Metadata mock integration

---

paimon-web-ui-new/mock/modules/metadata.js
paimon-web-ui-new/package.json
paimon-web-ui-new/src/api/models/catalog/index.ts
paimon-web-ui-new/src/api/models/catalog/types/table.ts
paimon-web-ui-new/src/components/dynamic-form/index.tsx
paimon-web-ui-new/src/components/dynamic-form/types.ts
paimon-web-ui-new/src/components/dynamic-form/use-form.ts
paimon-web-ui-new/src/components/modal/index.tsx
paimon-web-ui-new/src/form-lib/index.ts
paimon-web-ui-new/src/form-lib/metadata/use-options.ts
paimon-web-ui-new/src/store/catalog/index.ts
paimon-web-ui-new/src/views/metadata/components/catalog-form/index.tsx
paimon-web-ui-new/src/views/metadata/components/database-form/index.tsx
paimon-web-ui-new/src/views/metadata/components/menu-tree/index.module.scss
paimon-web-ui-new/src/views/metadata/components/menu-tree/index.tsx
paimon-web-ui-new/src/views/metadata/components/metadata-tabs/index.tsx
paimon-web-ui-new/src/views/metadata/components/options-form-content/index.tsx
paimon-web-ui-new/src/views/metadata/components/options-form/edit.tsx
paimon-web-ui-new/src/views/metadata/components/options-form/index.tsx
paimon-web-ui-new/src/views/metadata/components/options/index.tsx
paimon-web-ui-new/src/views/metadata/components/schema/index.tsx
paimon-web-ui-new/src/views/metadata/components/table-column-content/constant.ts
paimon-web-ui-new/src/views/metadata/components/table-column-content/index.tsx
paimon-web-ui-new/src/views/metadata/components/table-form/index.tsx
paimon-web-ui-new/src/views/metadata/constant.ts
paimon-web-ui-new/src/views/metadata/index.tsx

Supports Metadata options module finish & create table finish

[Feature] Enhance metadata options module support

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/TableController.java

Fix the code format problem of Class TableController.

[Improvement] Fix code style of TableController

---

paimon-web-ui-new/mock/modules/metadata.js
paimon-web-ui-new/src/api/message.ts
paimon-web-ui-new/src/api/models/catalog/index.ts
paimon-web-ui-new/src/api/models/catalog/types/table.ts
paimon-web-ui-new/src/api/request.ts
paimon-web-ui-new/src/components/modal/index.tsx
paimon-web-ui-new/src/views/metadata/components/catalog-form/index.tsx
paimon-web-ui-new/src/views/metadata/components/columns-form/index.tsx
paimon-web-ui-new/src/views/metadata/components/database-form/index.tsx
paimon-web-ui-new/src/views/metadata/components/datafile/index.tsx
paimon-web-ui-new/src/views/metadata/components/manifest/index.tsx
paimon-web-ui-new/src/views/metadata/components/options-form/edit.tsx
paimon-web-ui-new/src/views/metadata/components/options-form/index.tsx
paimon-web-ui-new/src/views/metadata/components/options/index.tsx
paimon-web-ui-new/src/views/metadata/components/schema/index.tsx
paimon-web-ui-new/src/views/metadata/components/snapshot/index.tsx
paimon-web-ui-new/src/views/metadata/components/table-column-content/index.tsx
paimon-web-ui-new/src/views/metadata/components/table-form/index.tsx
paimon-web-ui-new/src/views/metadata/components/table/index.tsx

Metadata Columns Add & Remove finish

[Feature] Enhance support adding and removing metadata column

---

paimon-web-ui-new/package.json
paimon-web-ui-new/pnpm-lock.yaml
paimon-web-ui-new/src/views/metadata/components/columns-form/index.tsx
paimon-web-ui-new/src/views/metadata/components/table-column-content/index.tsx

Support column sorting interaction.
https://github.com/apache/incubator-paimon-webui/assets/43628500/92d4c9a0-e587-43a4-887d-6960d360be3b

[Feature]  Support column sorting interaction

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/MetadataController.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/data/vo/OptionVO.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/MetadataService.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/MetadataServiceImpl.java
paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/MetadataControllerTest.java

close: #158 
add `/api/metadata/query/options` api for getting table options.
`MetadataControllerTest#testGetOptionInfo`

[Bugfix] Introduce getting table options interface

---

pom.xml

The name of the module was changed from paimon-web-ui-new to paimon-web-ui, but the entries related to paimon-web-ui-new were not removed from the pom file.

[Improvement] Remove unused entries from the pom file

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/data/vo/DataFileVO.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/data/vo/ManifestsVO.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/data/vo/SnapshotVO.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/MetadataServiceImpl.java
paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/MetadataControllerTest.java

The vo subsection of the metadata is currently incomplete. For example, DataFileVO lacks many fields. This PR completes the fields of VO.
- `MetadataControllerTest#testGetManifestInfo`
- `MetadataControllerTest#testGetDataFileInfo`
- `MetadataControllerTest#testGetSnapshotInfo`

[Improvement] Enhance alignment of metadata fields

---

paimon-web-server/src/main/resources/application.yml

close: https://github.com/apache/paimon-webui/issues/201
Disable full exposure of actuator endpoints to fix potential actuator vulnerability.

[Fix] Disable full exposure of actuator endpoints

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/DatabaseController.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/DatabaseService.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/DatabaseServiceImpl.java

Relates to: https://github.com/apache/paimon-webui/issues/205
This pull request aims to align the return types of our service layer interfaces with standard Spring framework practices by removing the use of a custom response wrapper (R). This change simplifies our service layer, ensuring it focuses solely on business logic and remains agnostic of HTTP response structures, as discussed in Issue #205.

[Improvement] Optimize return value type for database service interface

---

paimon-web-server/src/main/resources/application-dev-mysql.yml
paimon-web-ui/src/views/playground/components/query/components/menu-tree/index.module.scss
paimon-web-ui/src/views/playground/components/query/components/menu-tree/index.tsx

Complete dynamic menu tree Integration on query page.

[Feature] Support dynamic menu tree integration with query page

---

paimon-web-ui/.husky/pre-commit
paimon-web-ui/package.json

Support eslint checker before commit which could use the command `pnpm run format` to fixed.

[Featrue] Support frontend commit eslint checker

---

paimon-web-ui/src/views/playground/components/query/index.module.scss

fix the playground sroll tabs style

[Bugfix] Fix playground sroll tabs style

---

paimon-web-ui/src/api/models/job/index.ts
paimon-web-ui/src/api/models/job/types/history.ts
paimon-web-ui/src/views/playground/components/query/components/menu-tree/index.tsx

Introduce playground query history including fetching query history.
link #272

[Feature] Introduce playground query history

---

paimon-web-ui/src/api/models/catalog/index.ts
paimon-web-ui/src/api/models/catalog/types/table.ts
paimon-web-ui/src/locales/zh/modules/metadata.ts
paimon-web-ui/src/views/metadata/components/columns-form/index.tsx
paimon-web-ui/src/views/metadata/components/table-column-content/index.tsx
paimon-web-ui/vite.config.ts

close: https://github.com/apache/paimon-webui/issues/277
Support edit column.

[Feature] Support editing column 

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/data/model/BaseModel.java
scripts/sql/paimon-mysql.sql

fix: https://github.com/apache/paimon-webui/issues/308
Fix the problem of negative primary key.
Before:
After:

[Bugfix] Fix the problem of negative primary key

---

paimon-web-ui/src/views/metadata/components/table/index.tsx

close: https://github.com/apache/paimon-webui/issues/301
Optimize the table page display and increase height adaptation.

[Improvement] Optimize table page display and height adaptability

---

paimon-web-ui/src/views/metadata/components/menu-tree/index.module.scss
paimon-web-ui/src/views/metadata/index.module.scss
paimon-web-ui/src/views/metadata/index.tsx
paimon-web-ui/vite.config.ts

close: https://github.com/apache/paimon-webui/issues/303
The left navigation bar of metadata supports dragging and resizing.

[Improvement] Support left navigation bar of metadata with dragging and resizing

---

paimon-web-ui/src/form-lib/cdc/use-submit-cdc-job.ts

Support selecting a session cluster when submitting CDC jobs.  link issue #290
1. Configure the flink session cluster
2. Select the flink session cluster

[Improvement] Support selecting a session cluster when submitting CDC jobs

---

paimon-web-ui/src/views/system/cluster/components/cluster-form/index.tsx
paimon-web-ui/src/views/system/user/components/user-form/index.tsx

fix: https://github.com/apache/paimon-webui/issues/310
Fix the problem of inconsistent modal box names.

[Bugfix] Fix inconsistent modal box names

---

paimon-web-ui/src/form-lib/cdc/use-submit-cdc-job.ts

fix: https://github.com/apache/paimon-webui/issues/318
Fix front-end code formatting issues so other commits can be submitted.

[Bugfix] Fix frontend coding formatting style

---

paimon-web-ui/pnpm-lock.yaml
paimon-web-ui/src/api/models/catalog/types/table.ts
paimon-web-ui/src/components/dynamic-form/fields/checkbox.ts
paimon-web-ui/src/views/job/index.tsx
paimon-web-ui/src/views/metadata/components/table-form/index.tsx
paimon-web-ui/src/views/system/role/components/role-detail/index.tsx

[Bugfix] Fix the build error

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/JobServiceImpl.java

close: https://github.com/apache/paimon-webui/issues/316
1.remove unnecessary log printing.
2.optimize some update status codes.

[Improvement] Remove unnecessary log printing

---

paimon-web-server/pom.xml
pom.xml

close: https://github.com/apache/paimon-webui/issues/338
Dependency conflicts after packaging and deployment，this PR fixes the dependency conflict issue.

[Bugfix] Fix dependency conflicts

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/PaimonWebServerApplication.java

close: https://github.com/apache/paimon-webui/issues/342
- modify the main class annotation
- add EnableScheduling annotation

[Improvement] Add EnableScheduling annotation to main class

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/configrue/SaTokenConfigure.java

close: https://github.com/apache/paimon-webui/issues/340
Enable so-token configuration.

[Improvement] Enable so-token configuration

---

paimon-web-ui/vite.config.ts

Packaged static resources use relative paths to fit the server directory.

[Chore] Update build config

---

paimon-web-ui/src/views/login/use-form.ts

[Bugfix] Fix login page reload for clicking submit button

---

paimon-web-ui/src/views/metadata/components/columns-form/index.tsx
paimon-web-ui/src/views/metadata/components/table-column-content/index.tsx
paimon-web-ui/src/views/metadata/components/table-form/index.tsx

[Bugfix] Fix draggable

---

paimon-web-ui/.husky/pre-commit
paimon-web-ui/package.json
paimon-web-ui/pnpm-lock.yaml

[Improvement] Precommit should check ts and tsx file

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/data/model/MetadataFieldsModel.java
paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/MetadataControllerTest.java
paimon-web-ui/src/api/models/catalog/types/schema.ts
paimon-web-ui/src/views/metadata/components/schema/columns.ts

Issue: #361 
Unify comment field of table column.
`MetadataControllerTest#testGetSchemaInfo`
No.
No.

[Bugfix] Unify comment field of table column

---

paimon-web-ui/src/views/metadata/components/columns-form/index.tsx
paimon-web-ui/src/views/metadata/components/table-column-content/index.tsx

fix: https://github.com/apache/paimon-webui/issues/357
Fix mobile field order issue.

[Bugfix] Fix mobile field order

---

paimon-web-ui/src/views/metadata/components/manifest/index.tsx

close: https://github.com/apache/paimon-webui/issues/359
Adjust the width of manifest page fields.

[Improvement] Update width of manifest page fields

---

paimon-web-server/src/main/bin/start.sh

[Bugfix] correct typo in start.sh script.
No
No
No

[Bugfix] correct typo in start.sh script.

---

paimon-web-server/src/main/assembly/paimon-web-server.xml

Package the scripts directory together.
close #376

[Improvement] Support packaging scripts

---

paimon-web-ui/src/layouts/content/index.tsx
paimon-web-ui/src/views/playground/index.tsx

Front-end support for page caching can enhance the user experience. close #382 
Writing SQL.
Jump to other page.
Return to Sql query page.

[Impovement] Support page caching

---

paimon-web-ui/src/layouts/content/components/toolbar/index.tsx
paimon-web-ui/src/locales/en/modules/login.ts
paimon-web-ui/src/store/user/index.ts
paimon-web-ui/src/views/login/use-form.ts

[Feature] Support redirecting to login page

---

paimon-web-server/src/main/resources/application-dev-mysql.yml
paimon-web-server/src/main/resources/application-prod.yml

fix: https://github.com/apache/paimon-webui/issues/381
Fix connection lifetime exceeding issue by updating hikaricp settings.

[Bugfix] Fix connection lifetime exceeding issue by updating hikaricp settings

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/configrue/SaTokenConfigurer.java
paimon-web-server/src/main/resources/application.yml
paimon-web-server/src/test/java/org/apache/paimon/web/server/configurer/SaTokenConfigurerTests.java
paimon-web-server/src/test/resources/application.yml

Close #396 
- SaTokenConfigurerTests
No.
No.

[Improvement] Introduce interceptor.exclude.path.patterns to exclude path patterns for configurer interceptor

---

paimon-web-ui/src/api/models/catalog/types/catalog.ts
paimon-web-ui/src/views/metadata/components/catalog-form/index.tsx

fix: https://github.com/apache/paimon-webui/issues/371
Fix the problem of creating hive catalog

[Bugfix] Fix creating hive catalog

---

scripts/sql/paimon-mysql.sql

Close: https://github.com/apache/paimon-webui/issues/392
Support username field of user table unique key.
No

[Improvement] Support username field of user table unique key

---

paimon-web-server/src/main/bin/start.sh

close #405 
Add a help prompt to the start.sh

[Feature] Add a help prompt to the start.sh

---

paimon-web-api/pom.xml

Bump paimon version from 0.8.0 to 0.8.1.

[Improvement] Bump paimon version from 0.8.0 to 0.8.1

---

paimon-web-ui/src/api/models/catalog/index.ts
paimon-web-ui/src/api/models/catalog/types/database.ts
paimon-web-ui/src/locales/en/modules/metadata.ts
paimon-web-ui/src/locales/zh/modules/metadata.ts
paimon-web-ui/src/views/metadata/components/menu-tree/index.tsx
paimon-web-ui/vite.config.ts

close: https://github.com/apache/paimon-webui/issues/409
Introduce remove catalog, drop database, rename table and drop table for metadata.

[Feature] Introduce removing catalog, dropping database, renaming table and dropping table for metadata

---

paimon-web-ui/src/api/models/user/index.ts
paimon-web-ui/src/layouts/content/components/toolbar/index.tsx
paimon-web-ui/src/locales/en/modules/login.ts
paimon-web-ui/src/locales/zh/modules/login.ts
paimon-web-ui/src/store/user/index.ts
paimon-web-ui/src/views/login/use-form.ts

close: https://github.com/apache/paimon-webui/issues/411
Introduce changing user password.

[Feature] Introduce changing user password

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/context/logtool/LogEntity.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/JobService.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/JobServiceImpl.java

close: https://github.com/apache/paimon-webui/issues/418
Optimize job log code for backend.

[Improvement] Optimize job log

---

paimon-web-ui/package.json
paimon-web-ui/src/App.tsx
paimon-web-ui/src/api/models/job/index.ts
paimon-web-ui/src/store/job/index.ts
paimon-web-ui/src/views/playground/components/query/components/console/components/log/index.module.scss
paimon-web-ui/src/views/playground/components/query/components/console/components/log/index.tsx
paimon-web-ui/src/views/playground/components/query/components/console/index.module.scss
paimon-web-ui/src/views/playground/components/query/components/console/index.tsx
paimon-web-ui/src/views/playground/components/query/index.tsx
paimon-web-ui/vite.config.ts

close: https://github.com/apache/paimon-webui/issues/416
Introduce job log console for frontend.

[Feature] Introduce job log console

---

paimon-web-ui/src/views/metadata/components/menu-tree/index.tsx

[Bugfix] Fix search mode error

---

paimon-web-ui/src/views/login/use-form.ts

fix the blank page after login success

[Bugfix] Fix blank page after login success

---

paimon-web-ui/src/assets/styles/main.scss

[Bugfix] Fix copy error

---

paimon-web-api/pom.xml
paimon-web-api/src/main/java/org/apache/paimon/web/api/action/context/factory/MysqlSyncDatabasesActionContextFactory.java
paimon-web-api/src/main/resources/META-INF/services/org.apache.paimon.web.api.action.context.factory.FlinkCdcActionContextFactory
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/CdcJobDefinitionServiceImpl.java
paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/CdcJobDefinitionControllerTest.java
pom.xml

close #427 
A factory has been added to facilitate the implementation of full MySQL database synchronization.
Add test case org.apache.paimon.web.server.controller.CdcJobDefinitionControllerTest#submitDatabaseSyncCdcJob
No change

[Feature] CDC integration supports full mysql database synchronization

---

paimon-web-api/src/main/java/org/apache/paimon/web/api/action/context/FlinkCdcTableSyncActionContext.java
paimon-web-api/src/main/java/org/apache/paimon/web/api/action/context/factory/PostgresSyncTableActionContextFactory.java
paimon-web-api/src/main/java/org/apache/paimon/web/api/action/context/options/FlinkCdcOptions.java
paimon-web-api/src/main/java/org/apache/paimon/web/api/enums/FlinkCdcDataSourceType.java
paimon-web-api/src/main/resources/META-INF/services/org.apache.paimon.web.api.action.context.factory.FlinkCdcActionContextFactory
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/CdcJobDefinitionServiceImpl.java
paimon-web-ui/src/assets/styles/main.scss

close: #436 
Support Postgres CDC
NO. 
NO.
NO.

[Feature] Support Postgres CDC

---

paimon-web-server/pom.xml
paimon-web-server/src/main/java/org/apache/paimon/web/server/configrue/WebSocketConfig.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/data/dto/JobSubmitDTO.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/data/model/JobInfo.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/data/vo/JobVO.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/JobServiceImpl.java
paimon-web-server/src/main/resources/application.yml
paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/JobControllerTest.java
scripts/sql/paimon-mysql.sql

close: https://github.com/apache/paimon-webui/issues/439
Introduce websocket for job submission.
JobControllerTest#testGetJobStatistics

[Feature] Introduce web socket for job submission

---

paimon-web-ui/src/views/playground/components/query/components/debugger/index.tsx

close: https://github.com/apache/paimon-webui/issues/443
Run button to add loading.

[Improvement] Add loading for run button

---

paimon-web-ui/src/api/models/job/index.ts
paimon-web-ui/src/locales/en/modules/playground.ts
paimon-web-ui/src/locales/zh/modules/playground.ts
paimon-web-ui/src/views/playground/components/query/components/console/index.tsx

close: https://github.com/apache/paimon-webui/issues/445
Added clear log function on the front end.

[Feature] Introduce log cleaner for logging query

---

paimon-web-ui/src/store/job/index.ts
paimon-web-ui/src/store/job/type.ts
paimon-web-ui/src/views/playground/components/query/components/console/components/controls/index.tsx
paimon-web-ui/src/views/playground/components/query/components/console/components/table/index.tsx

close: https://github.com/apache/paimon-webui/issues/449
Add loading to query results.

[Improvement] Add loading to query results

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/JobController.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/JobService.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/JobServiceImpl.java
paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/JobControllerTest.java
paimon-web-server/src/test/resources/application.yml

close: https://github.com/apache/paimon-webui/issues/447
Added clear log function on the back end.
- `JobControllerTest#testGetLogs`
- `JobControllerTest#testClearLogs`
```
@SaIgnore
@GetMapping("/logs/clear")
public R<String> clearLogs() {
return R.succeed(jobService.clearLog(StpUtil.getLoginIdAsString()));
}
```

[Feature] Introduce log cleaner interface

---

.github/workflows/backend-ci.yml
.github/workflows/frontend-ci.yml
.github/workflows/pre-release.yml
paimon-web-ui/.husky/pre-commit
paimon-web-ui/package.json

Refactor CI
1. Split release and regular push,pull request
2. Create front-end check CI
3. Split front-end check CI and back-end check CI

[Improvement] Refactor CI

---

paimon-web-ui/src/layouts/content/components/menubar/index.tsx
paimon-web-ui/src/views/playground/components/query/index.tsx

fix: https://github.com/apache/paimon-webui/issues/454
Fix the problem of front-end packaging type check failure.

[Bugfix] Fix type check failure

---

paimon-web-ui/.vscode/settings.json
paimon-web-ui/package.json
paimon-web-ui/pnpm-lock.yaml
paimon-web-ui/src/composables/useWebSocket.ts
paimon-web-ui/src/layouts/content/index.tsx
paimon-web-ui/src/store/job/index.ts
paimon-web-ui/src/views/cdc/components/dag/dag-slider.tsx
paimon-web-ui/src/views/cdc/components/dag/index.tsx
paimon-web-ui/src/views/metadata/index.tsx
paimon-web-ui/src/views/playground/components/query/components/console/components/controls/index.tsx
paimon-web-ui/src/views/playground/components/query/components/console/index.tsx
paimon-web-ui/src/views/playground/components/query/components/debugger/index.tsx
paimon-web-ui/src/views/playground/components/query/index.tsx
paimon-web-ui/src/views/system/role/components/role-detail/index.tsx

- Fix the Frontend CI error
- Fix the space lint error
- Fix the parenthesis lint error

[Bugfix] Fix CI error

---

paimon-web-ui/pom.xml

[Bugfix] Use build-only to build the frontend

---

paimon-web-api/pom.xml
paimon-web-engine/paimon-web-engine-flink/pom.xml
pom.xml

close: https://github.com/apache/paimon-webui/issues/463
The current package is a bit large after packaging. Optimize some dependencies to reduce the size of the package.

 [Improvement] Optimize some dependencies to reduce the size of the package

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/JobController.java

close: #465 
Remove permission check for job log interface.
No.
No.
No.

[Bugfix] Remove permission check for job log interface

---

paimon-web-ui/src/layouts/content/index.tsx

close: https://github.com/apache/paimon-webui/issues/470
Fixed sidebar layout issue.

[Bugfix] Fix sidebar layout

---

paimon-web-ui/src/views/cdc/components/list/index.tsx

[Bugfix] Keep-alive causing page transitions without refreshing.

---

paimon-web-ui/src/views/playground/components/query/components/debugger/index.tsx

fix: https://github.com/apache/paimon-webui/issues/485
Fix the loading state of the submit button

[Bugfix] Fix the loading state of the submit button

---

paimon-web-ui/src/views/system/user/index.tsx

close: https://github.com/apache/paimon-webui/issues/479
Optimize the new user button and add icon.

[Improvement] Optimize creating user button with icon

---

paimon-web-server/src/main/resources/mapper/ClusterMapper.xml

close: https://github.com/apache/paimon-webui/issues/477
Backend completes cluster query fields.

[Improvement] Enhance cluster query fields with deploymentMode

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/configrue/GlobalExceptionHandler.java

close: #499 
Fix prompt language when deleting users

[Bugfix] Fix prompt language when deleting users

---

paimon-web-server/src/main/java/org/apache/paimon/web/server/data/model/User.java
paimon-web-server/src/main/resources/mapper/UserMapper.xml
paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/UserControllerTest.java
scripts/sql/paimon-mysql.sql

close: #497 
Error reported when adding another user with the same username after deleting the user
No.
No.
No.

[Bugfix] Fix adding user failure

---

paimon-web-ui/src/views/system/cluster/index.tsx
paimon-web-ui/src/views/system/user/index.tsx

[Bugfix] Fix missing create time and update time for editing table data

---

paimon-web-ui/src/views/system/cluster/components/cluster-form/index.tsx

[Bugfix] Fix deploymentMode can not render correct for editing cluster

---

paimon-web-ui/src/api/models/job/types/job.ts
paimon-web-ui/src/locales/en/modules/playground.ts
paimon-web-ui/src/locales/zh/modules/playground.ts
paimon-web-ui/src/views/playground/components/query/components/debugger/index.module.scss
paimon-web-ui/src/views/playground/components/query/components/debugger/index.tsx
paimon-web-ui/src/views/playground/components/query/components/tabs/index.module.scss

[Feature] Frontend supports query limit

---

paimon-web-ui/pom.xml

[Bugfix] Fix maven build of paimon-web-ui module

---

scripts/sql/paimon-mysql.sql

close: #516 
refer: #498 
Error executing SQL script, table 'user' does not have 'isDelete' field.
No.
No.
No.

[Bugfix] Fix SQL script of user table

---

paimon-web-dist/src/main/assembly/paimon-web-bin.xml
paimon-web-server/pom.xml
paimon-web-server/src/main/assembly/paimon-web-server.xml

close #519 
Remove the ui in paimon-web-server

[Improvement] Optimize packaging

---

docs/src/guide/quick-start.md

[Bugfix] Fix document typo

---

paimon-web-engine/paimon-web-engine-flink/paimon-web-engine-flink-sql-gateway/src/main/java/org/apache/paimon/web/engine/flink/sql/gateway/executor/FlinkSqlGatewayExecutor.java
paimon-web-server/src/main/java/org/apache/paimon/web/server/context/logtool/LogReadPool.java
paimon-web-ui/src/views/playground/components/query/index.tsx

1. fix playground npe bug
2. fix render nothing where run "show tables" sql
1. run a one-liner command, for example, to register a catalog, set a variable, and suppress the output.
2. run a multi-liner command, for example, to register a catalog, set a variable, get metadata 
3. run one-liner command to get data result
4. run multi-liner command to get data result
5. run error sql

[Bugfix] Fix playground NullPointerException

---

docs/src/guide/quick-start.md

close: https://github.com/apache/paimon-webui/issues/532
NO
No
Regarding dependencies excluded during packaging, such as necessary packages for creating catalogs like OSS and S3, there is currently no explanation in the documentation. To make it easier for users to download the relevant dependencies as needed, it is recommended to supplement the documentation with this information.

[Improvement] [doc] Enhance the documentation to include details about non-packaged dependencies 

---

pom.xml

Introduce apache-release and docs-and-source profile to release paimon webui.
No.
No.
No.

[Improvement] Introduce apache-release and docs-and-source profile

---

pom.xml

Remove `project.version` property.
No.
No.
No.

[Improvement] Remove project.version property
