paimon-web-ui-new/src/layouts/content/components/menubar/index.tsx, paimon-web-ui-new/src/router/modules/cdc_ingestion.ts, paimon-web-ui-new/src/store/config/index.ts, paimon-web-ui-new/src/store/config/type.ts, paimon-web-ui-new/src/views/cdc/index.module.scss, paimon-web-ui-new/src/views/cdc/index.tsx, paimon-web-ui-new/src/views/login/use-form.ts, paimon-web-ui-new/src/views/metadata/components/metadata-tabs/index.tsx, paimon-web-ui-new/src/views/playground/components/query/components/console/index.tsx, paimon-web-ui-new/src/views/playground/components/workbench/components/console/index.tsx, paimon-web-ui-new/src/views/system/index.module.scss, paimon-web-ui-new/src/views/system/index.tsx
1. fix some errors
- The page route refresh status is lost
- Console warning about tab
- Query page style error
2. add new page for cdc and system
=> [Feature] Introduce new page for cdc and system

paimon-web-ui-new/src/components/modal/index.tsx, paimon-web-ui-new/src/views/cdc/components/dag/index.tsx, paimon-web-ui-new/src/views/cdc/components/list/index.tsx, paimon-web-ui-new/src/views/cdc/index.tsx
1.Fix dynamic form binding error
2.Add new dag page and route
Please refer to the main `issue`  [#77 ](https://github.com/apache/incubator-paimon-webui/issues/77).
=> [Feature] Introduce new dag page and route

paimon-web-ui-new/src/views/metadata/components/datafile/index.tsx, paimon-web-ui-new/src/views/metadata/components/manifest/index.tsx, paimon-web-ui-new/src/views/metadata/components/menu-tree/index.tsx, paimon-web-ui-new/src/views/metadata/components/metadata-tabs/index.tsx, paimon-web-ui-new/src/views/metadata/components/snapshot/index.tsx
Enhance metadata manifest info & snapshot info & datafile
Manifest Info style 
SnapShot Info style
DataFile style
Menu Tree point area expansion
=> [Feature]: Enhance metadata manifest info & snapshot info & datafile 

paimon-web-ui-new/src/api/models/catalog/index.ts, paimon-web-ui-new/src/api/models/catalog/types/catalog.ts, paimon-web-ui-new/src/api/models/catalog/types/database.ts, paimon-web-ui-new/src/api/models/catalog/types/datafile.ts, paimon-web-ui-new/src/api/models/catalog/types/index.ts, paimon-web-ui-new/src/api/models/catalog/types/manifest.ts, paimon-web-ui-new/src/api/models/catalog/types/schema.ts, paimon-web-ui-new/src/api/models/catalog/types/snapshot.ts, paimon-web-ui-new/src/api/models/catalog/types/table.ts
Split MetaData module type. Predefined of schema, manifest, datafile, snapshot type.
=> [Improvement] Split MetaData module type

paimon-web-ui-new/src/layouts/content/index.tsx
Fixed a bug with front-end rendering 0
=> [Bugfix] Fix rendering 0 of showing side

paimon-web-ui-new/src/api/models/catalog/index.ts, paimon-web-ui-new/src/api/models/catalog/types/table.ts, paimon-web-ui-new/src/api/request.ts, paimon-web-ui-new/src/store/catalog/index.ts, paimon-web-ui-new/src/views/metadata/components/breadcrumb/index.tsx, paimon-web-ui-new/src/views/metadata/components/datafile/index.tsx, paimon-web-ui-new/src/views/metadata/components/manifest/index.tsx, paimon-web-ui-new/src/views/metadata/components/menu-tree/index.tsx, paimon-web-ui-new/src/views/metadata/components/schema/index.tsx, paimon-web-ui-new/src/views/metadata/components/snapshot/index.tsx, paimon-web-ui-new/src/views/metadata/index.module.scss, paimon-web-ui-new/src/views/metadata/index.tsx
supports Metadata module left and right linkage
Metadata module will be show Empty Page when You don't pick the Table
=> [Feature] Support metadata module left and right linkage and empty

paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/MetadataControllerTest.java
The Metadata test case API still uses the interface address of the old version and does not correspond to the current API.
fix #127
=> [Bugfix] Fix metadata tests have no corresponding modifications via latest metadata interface

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/TableController.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/data/vo/TableVO.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/TableService.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/TableServiceImpl.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/TableControllerTest.java
Since the listTables interface does not return column-related information, the front-end currently cannot obtain column details. If column information is returned in the listTables interface, the front-end cannot refresh the data when switching tables, so an interface to obtain column information is added here.
TableControllerTest#testListColumns
=> [Feature] Add list columns interface

paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/CatalogControllerTest.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/CdcJobDefinitionControllerTest.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/DatabaseControllerTest.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/SysMenuControllerTest.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/SysRoleControllerTest.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/TableControllerTest.java
The java doc of tests in server module should be unified with {@link} to represent the class which the test is veriied for.
- Before：
```
/** Test for CatalogController. */
@SpringBootTest
@AutoConfigureMockMvc
public class CatalogControllerTest extends ControllerTestBase {
...
}
```
- After:
```
/** Test for {@link CatalogController}. */
@SpringBootTest
@AutoConfigureMockMvc
public class CatalogControllerTest extends ControllerTestBase {
...
}
```
- `CatalogControllerTest`
- `CdcJobDefinitionControllerTest`
- `DatabaseControllerTest`
- `SysMenuControllerTest`
- `SysRoleControllerTest`
- `TableControllerTest`
No.
No.
=> [Improvement] Unify java doc of tests in server module via {@link} annotation

paimon-web-ui-new/mock/modules/metadata.js, paimon-web-ui-new/src/api/models/catalog/index.ts
close: #157 
API `/catalog/getAllCatalogs` no longer exists since [#99](https://github.com/apache/incubator-paimon-webui/pull/99/files#diff-af0684c9eb5b74942099db6a17667ba11365f3ecd1ced37eca4cb6fceef026d1R71) change it to `/catalog/list`
=> [Bugfix] Fix request path of list catalogs interface

paimon-web-api/src/main/java/org/apache/paimon/web/api/catalog/PaimonServiceFactory.java, paimon-web-api/src/main/java/org/apache/paimon/web/api/common/CatalogProperties.java
Close: #164 
The value of `OSS_ACCESS_KEY` and `OSS_SECRET_KEY` are reversed.
=> [Bugfix] Fix swapped OSS_ACCESS_KEY and OSS_SECRET_KEY

.gitignore
close: https://github.com/apache/incubator-paimon-webui/issues/172
The name of the module was changed from paimon-web-ui-new to paimon-web-ui, but the related entries in the .gitignore file have not been updated to reflect this change. This can cause files and directories to be tracked by Git that should be ignored when expected.
Items that need to be updated include but are not limited to:
- paimon-web-ui-new/auto-imports.d.ts
- paimon-web-ui-new/httpData
- paimon-web-ui-new/apiWeb.json
=> [Fix] Update .gitignore file to reflect module renamed to paimon-web-ui

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/UserController.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/UserService.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/UserServiceImpl.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/UserControllerTest.java
close: https://github.com/apache/paimon-webui/issues/203
Add the user password change api.
UserControllerTest#testChangePassword.
```
/**
* Changes a user's password.
*
* @param user the user object containing the new password
* @return a response entity indicating success or failure
*/
@SaCheckPermission("system:user:change:password")
@PostMapping("/change/password")
public R<Void> changePassword(@Validated @RequestBody User user) {
if (userService.getUserById(user.getId()) == null) {
return R.failed(USER_NOT_EXIST);
}
return userService.changePassword(user) ? R.succeed() : R.failed();
}
```
=> [Feature] Add the user password change api

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/CatalogController.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/CatalogService.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/CatalogServiceImpl.java
Relates to: https://github.com/apache/paimon-webui/issues/205
This pull request aims to align the return types of our service layer interfaces with standard Spring framework practices by removing the use of a custom response wrapper (R). This change simplifies our service layer, ensuring it focuses solely on business logic and remains agnostic of HTTP response structures, as discussed in Issue #205.
=> [Improvement] Optimize return value type for catalog service interface

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/TableController.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/TableService.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/TableServiceImpl.java
Relates to: https://github.com/apache/paimon-webui/issues/205
This pull request aims to align the return types of our service layer interfaces with standard Spring framework practices by removing the use of a custom response wrapper (R). This change simplifies our service layer, ensuring it focuses solely on business logic and remains agnostic of HTTP response structures, as discussed in Issue #205.
=> [Improvement] Optimize return value type for table service interface

paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/UserServiceImpl.java
close: https://github.com/apache/paimon-webui/issues/210
The user password is not encrypted for creation of user at present. Therefore, the password should be encrypted before saving user.
=> [Improvement] Encrypt user password before saving user

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/SysMenuController.java, scripts/sql/paimon-mysql.sql
close: https://github.com/apache/paimon-webui/issues/216
Currently, the interface method names of menu management are not unified with other interfaces of system management. In order to make the interface definition more standardized, the interface method names of menu management are unified here.
=> [Improvement] Align naming of menu interface with system management conventions

paimon-web-server/src/main/java/org/apache/paimon/web/server/data/vo/UserInfoVO.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/UserServiceImpl.java
close: https://github.com/apache/paimon-webui/issues/214
When the frontend does button-level permission management, the back-end needs to return all permission strings of the current user. Currently, the login interface does not return the user's permission string, so it is necessary to return the user's permission string after logging in.
=> [Improvement]  Support permissions setting to UserInfoVO

paimon-web-api/pom.xml, pom.xml
Bump Paimon version from 0.6-SNAPSHOT to 0.8.0.
Paimon v0.8.0 has been released, which should bump Paimon version from 0.6-SNAPSHOT.
None.
None.
=> [Feature] Bump Paimon version from 0.6-SNAPSHOT to 0.8.0

paimon-web-server/pom.xml, paimon-web-server/src/main/java/org/apache/paimon/web/server/configrue/RetryConfig.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/SessionController.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/data/dto/SessionDTO.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/SessionService.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/UserSessionManager.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/SessionServiceImpl.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/FlinkSQLGatewayTestBase.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/SessionControllerTest.java
Relates to: #195
This pull request is a subtask implementation of #195, which introduces a session interface that creates a session or triggers a heartbeat of session.
`SessionControllerTest`
```
@PostMapping("/check")
public R<Void> checkAndRenewSession(Integer uid) {
QueryWrapper<ClusterInfo> queryWrapper = new QueryWrapper<>();
queryWrapper.eq("type", "Flink");
List<ClusterInfo> clusterInfos = clusterService.list(queryWrapper);
for (ClusterInfo cluster : clusterInfos) {
SessionDTO sessionDTO = new SessionDTO();
sessionDTO.setHost(cluster.getHost());
sessionDTO.setPort(cluster.getPort());
sessionDTO.setClusterId(cluster.getId());
sessionDTO.setUid(uid);
if (sessionService.getSession(uid, cluster.getId()) == null) {
sessionService.createSession(sessionDTO);
} else {
if …
```
=> [Feature] Introduce Session Interface

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/UserController.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/UserService.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/UserServiceImpl.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/UserControllerTest.java
close: https://github.com/apache/paimon-webui/issues/223
At present, the user interface does assign roles to users and modify user status interfaces. These two interfaces need to be added and front-end joint debugging.
UserControllerTest#testAllocateRole.
UserControllerTest#testChangeUserStatus.
```
* Changes the status of a user via a PUT request.
*
* @param user the user object containing the new status information
* @return a response object indicating success or failure
*/
@SaCheckPermission("system:user:update")
@PutMapping("/changeStatus")
public R<Void> changeStatus(@RequestBody User user) {
return userService.updateUserStatus(user) ? R.succeed() : R.failed();
}
/**
* Allocates a role to a user.
*
* @param user the user to whom the role is to be allocated
* @return a response …
```
=> [Improvement] Support changing status and assigning role of user 

scripts/sql/paimon-mysql.sql
close: https://github.com/apache/paimon-webui/issues/225
Currently, the menu names in the menu table are separated by spaces. They need to be separated by underscores. The front end needs to use this as the key in the internationalization file.
=> [Improvement] Refactor menu_name to use underscores for consistency

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/CatalogController.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/CdcJobDefinitionController.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/DatabaseController.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/MetadataController.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/TableController.java
Some interfaces were previously developed without permission annotations. This PR completes the permission annotations of the interface and is used to control user permissions.
=> [Improvement] Add permission annotation for interface

paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/SysRoleServiceImpl.java
There is no default value assigned to the sort field of the role. You need to assign a value to the sort field when the backend creates the role.
=> [Improvement] Support assigning sort field with value when creating a role

paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/JobServiceImpl.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/JobControllerTest.java
close: https://github.com/apache/paimon-webui/issues/267
Fill in the execution mode for statement. If the front-end selects the execution mode as Streaming, the back-end fills in SET 'execution.runtime-mode' = 'streaming' for statement; If the front-end selects the execution mode as Batch, the back-end fills in SET 'execution.runtime-mode' = 'batch' for statement;
=> [Improvement] Fill in the execution mode for the statement

paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/TableServiceImpl.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/TableControllerTest.java
close: https://github.com/apache/paimon-webui/issues/279
Fixed the bug that table cannot be created without partition key.
TableControllerTest#testCreateTable.
=> [Bugfix] Fix creating table without partition key

paimon-web-ui/src/views/metadata/components/schema/index.tsx, paimon-web-ui/src/views/metadata/components/snapshot/index.tsx, paimon-web-ui/src/views/metadata/index.module.scss
close: https://github.com/apache/paimon-webui/issues/281
Align the fields displayed on the Snapshot page with the backend.
=> [Improvement] Align field names displayed on the Snapshot page with the backend interface

paimon-web-ui/src/views/metadata/components/table-form/index.tsx
close: https://github.com/apache/paimon-webui/issues/305
Adjust the width of the created table page to avoid scroll bars
Before:
After:
=>  [Improvement] Adapt width of the created table page to avoid scroll bars

paimon-web-ui/src/views/metadata/components/manifest/index.tsx
close: https://github.com/apache/paimon-webui/issues/283
Align the fields displayed on the Menifest page with the backend.
=> [Improvement] Align field names displayed on the Manifest page with the backend interface

paimon-web-ui/src/views/metadata/components/options/index.tsx
close: https://github.com/apache/paimon-webui/issues/299
Optimize the display position of option page fields.
Before:
After:
=> [Improvement] Optimize the display position of option page fields

paimon-web-server/src/main/java/org/apache/paimon/web/server/data/dto/CdcJobSubmitDTO.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/CdcJobDefinitionServiceImpl.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/CdcJobDefinitionControllerTest.java
Support selecting a session cluster when submitting CDC jobs . Link issue #290 
No change
```java
@PostMapping("{id}/submit")
public R<Void> submit(@PathVariable Integer id, @RequestBody CdcJobSubmitDTO cdcJobSubmitDTO) {
return cdcJobDefinitionService.submit(id, cdcJobSubmitDTO);
}
```
=> [Improvement] Support selecting a session cluster when submitting CDC jobs

paimon-web-server/src/main/java/org/apache/paimon/web/server/configrue/MybatisPlusMetaObjectHandler.java, paimon-web-server/src/main/resources/mapper/SysRoleMapper.xml, paimon-web-server/src/main/resources/mapper/UserMapper.xml, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/SysRoleControllerTest.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/UserControllerTest.java
Issue: #312 
1.  Fix the issue where the update time field on the user management list page and role management list page is displayed as null.
2.  Fix the updateTime field being null when inserting data.
- `SysRoleControllerTest#testQueryRole`
- `SysRoleControllerTest#getRoleList`
- `UserControllerTest#getUser`
- `UserControllerTest#testListUsers`
No.
No.
=> [Bugfix] Add updateTime field into Mapper

.gitignore, paimon-web-dist/pom.xml, paimon-web-dist/src/main/assembly/paimon-web-bin.xml, paimon-web-dist/src/main/assembly/paimon-web-src.xml, paimon-web-server/pom.xml, paimon-web-server/src/main/assembly/paimon-web-server.xml, paimon-web-server/src/main/bin/env.sh, paimon-web-server/src/main/bin/start.sh, paimon-web-ui/pom.xml, pom.xml
Use assembly to build when profile is release. close #259
=> [Feature] Use assembly to build source code via release profile

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/CdcJobDefinitionController.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/JobController.java
close: https://github.com/apache/paimon-webui/issues/326
Some functional interfaces do not require menu permissions and do not require permission control. Adding permission control will make the interface inaccessible, so the permission control annotation needs to be removed.
=> [Improvement] Remove permission control annotations

paimon-web-ui/src/views/metadata/components/datafile/index.tsx
close: https://github.com/apache/paimon-webui/issues/284
Align field names displayed on the DataFile page with the backend interface.
=> [Improvement] Align field names displayed on the DataFile page with the backend interface

paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/SessionController.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/SessionControllerTest.java
close: https://github.com/apache/paimon-webui/issues/366
Get the logged in user's id from the so-token context .
- `SessionControllerTest#testCreateSession`
- `SessionControllerTest#testDropSession`
=> [Improvement] Get the logged in user's id from the so-token context 

paimon-web-ui/src/views/playground/components/query/components/debugger/index.tsx, paimon-web-ui/src/views/playground/components/query/index.tsx
close: https://github.com/apache/paimon-webui/issues/333
The front-end obtains the job status scheduled task without a stop method, and it will continue to schedule and request the back-end interface, which is unreasonable.This PR adds a stop method for the scheduled task that obtains the job status on the front end.
According to the data printed by the browser console, the modification of this PR can work.
=> [Bugfix] Support stopping getting job status with scheduling task

paimon-web-ui/src/router/index.ts
close #372 
Front-end routing configuration mistake: the import.meta.env.BASE_URL always stays as /, resulting in incorrect page rendering.
```ts
const router = createRouter({
history: createWebHistory(import.meta.env.BASE_URL),
routes,
})
```
=> [Bugfix] Fix routing errors

paimon-web-server/src/main/bin/start.sh
Close #379.
Support the `start.sh` script to support daemon deployment.
Daemon deployment. Run bin/start.sh --daemon
Foreground deployment. Run bin/start.sh
=> [Impovement] Support start.sh script deployment in daemon

paimon-web-ui/src/layouts/content/index.tsx, paimon-web-ui/src/layouts/content/use-data.ts, paimon-web-ui/src/router/routes.ts, paimon-web-ui/src/store/config/index.ts, paimon-web-ui/src/store/config/type.ts, paimon-web-ui/src/store/user/index.ts, paimon-web-ui/src/views/login/use-form.ts, paimon-web-ui/src/views/system/role/components/role-form/index.tsx, paimon-web-ui/src/views/system/user/components/user-form/index.tsx
close #403 
Permission management is not functioning properly, as there is a dependency relationship between parent and child nodes when selecting the role tree. When rendering the interface, it fails to render according to the permissions granted.
Currently, low-privilege users are able to view and access menus that they have permission for.
=> [Bugfix] Fix permission management

paimon-web-ui/src/api/models/session/index.ts, paimon-web-ui/src/views/playground/components/query/index.tsx
Close: #331
Support scheduled tasks for frontend.
The task status displayed on the page changes, indicating that the scheduled task to refresh the task status is working.
Printing from the console can also verify that the scheduled task can work.
Create a session scheduled task print.
=> [Feature] Support scheduled tasks for frontend

paimon-web-ui/src/layouts/content/components/toolbar/index.tsx
close: https://github.com/apache/paimon-webui/issues/420
Adjust the header toolbar to be centered vertically.
=> [Improvement] Adjust the header toolbar to be centered vertically

paimon-web-server/src/main/java/org/apache/paimon/web/server/configrue/JacksonConfig.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/configurer/JacksonConfigTests.java
Close: #451 
Unify global LocalDateTime format
- `JacksonConfigTests#testLocalDateTimeSerialization`
- `JacksonConfigTests#testLocalDateTimeDeserialization`
- `JacksonConfigTests#testInvalidLocalDateTimeDeserialization`
No.
No.
No.
=> [Bugfix] Unify global LocalDateTime format

paimon-web-server/pom.xml, paimon-web-server/src/main/java/org/apache/paimon/web/server/controller/SessionController.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/JobServiceImpl.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/JobControllerTest.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/controller/SessionControllerTest.java
close: https://github.com/apache/paimon-webui/issues/483
When creating a cluster, deploymentMode is added to distinguish different deployment modes, so the query module obtains the cluster name through deploymentMode.
- `JobControllerTest#before`
- `SessionControllerTest#testCreateSession`
=> [Improvement] Support SessionController and JobController obtaining cluster through deployment mode

paimon-web-server/src/main/java/org/apache/paimon/web/server/data/model/SysRole.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/SysRoleServiceImpl.java
close: https://github.com/apache/paimon-webui/issues/472
The back end adds indeterminate keys to the permission configuration of role creation.
=> [Improvement] Support indeterminate keys with the permission configuration of role creation

paimon-web-ui/src/api/models/role/types.ts, paimon-web-ui/src/views/system/role/components/role-form/index.tsx, paimon-web-ui/src/views/system/role/index.tsx
close: https://github.com/apache/paimon-webui/issues/472
The front end adds indeterminate keys to the permission configuration of role creation.
=> [Improvement] Support indeterminate keys for permission configuration of role creation

paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/ClusterServiceImpl.java
close: https://github.com/apache/paimon-webui/issues/490
The checkClusterHeartbeatStatus method in the cluster interface prints info logs every 1 minute. This PR removes unnecessary log printing in the cluster interface.
=> [Improvement] Remove unnecessary logging of cluster interface

paimon-web-ui/src/api/models/cluster/index.ts, paimon-web-ui/src/views/playground/components/query/components/debugger/index.tsx
close: https://github.com/apache/paimon-webui/issues/481
When creating a cluster, deploymentMode is added to distinguish different deployment modes, so the query module obtains the cluster name through deploymentMode.
=> [Improvement] The query module obtains the cluster name through deploymentMode

.github/workflows/frontend-ci.yml
[Bugfix] fix CI
Replace CI npm to pnpm
=> [Bugfix] Fix CI

paimon-web-server/src/main/java/org/apache/paimon/web/server/configrue/JacksonConfig.java, paimon-web-server/src/test/java/org/apache/paimon/web/server/configurer/JacksonConfigTests.java
close: #495 
Unify global date format.
- `JacksonConfigTests#testLocalDateSerialization`
- `JacksonConfigTests#testLocalDateDeserialization`
- `JacksonConfigTests#testLocalTimeSerialization`
- `JacksonConfigTests#testLocalTimeDeserialization`
- `JacksonConfigTests#testDateSerialization`
- `JacksonConfigTests#testDateDeserialization`
No.
No.
=> [Improvement] Unify global date format

paimon-web-engine/paimon-web-engine-flink/paimon-web-engine-flink-common/src/main/java/org/apache/paimon/web/engine/flink/common/executor/Executor.java, paimon-web-engine/paimon-web-engine-flink/paimon-web-engine-flink-common/src/main/java/org/apache/paimon/web/engine/flink/common/parser/CustomSqlParser.java, paimon-web-engine/paimon-web-engine-flink/paimon-web-engine-flink-common/src/test/java/org/apache/paimon/web/engine/flink/common/parser/CustomSqlParserTest.java, paimon-web-engine/paimon-web-engine-flink/paimon-web-engine-flink-common/src/test/java/org/apache/paimon/web/engine/flink/common/parser/StatementsConstant.java, paimon-web-engine/paimon-web-engine-flink/paimon-web-engine-flink-sql-gateway/src/main/java/org/apache/paimon/web/engine/flink/sql/gateway/executor/FlinkSqlGatewayExecutor.java, paimon-web-engine/paimon-web-engine-flink/paimon-web-engine-flink-sql-gateway/src/test/java/org/apache/paimon/web/engine/flink/sql/gataway/executor/FlinkSqlGatewayExecutorTest.java, paimon-web-engine/paimon-web-engine-flink/pom.xml, paimon-web-server/pom.xml, paimon-web-server/src/main/java/org/apache/paimon/web/server/data/dto/JobSubmitDTO.java, paimon-web-server/src/main/java/org/apache/paimon/web/server/service/impl/JobServiceImpl.java
close: https://github.com/apache/paimon-webui/issues/501
Apache Calcite is introduced in the backend to support query limits.
- `CustomSqlParserTest`.
- `FlinkSqlGatewayExecutorTest`
```
/**
* Executes an SQL statement.
*
* @param statement The SQL statement to be executed.
* @param maxRows The maximum number of rows to return in the result set.
* @return SubmitResult containing information about the execution result.
* @throws Exception if there is an error executing the SQL statement.
*/
ExecutionResult executeSql(String statement, int maxRows) throws Exception;
```
=> [Improvement] Support query limit

tools/releasing/create_release_branch.sh, tools/releasing/create_source_release.sh, tools/releasing/deploy_staging_jars.sh, tools/releasing/update_branch_version.sh
Support releasing scripts of Paimon WebUI to release version. Follow the process of [Creating a Paimon Release](https://cwiki.apache.org/confluence/display/PAIMON/Creating+a+Paimon+Release).
No.
No.
No.
=> [Release] Support releasing scripts of Paimon WebUI

paimon-web-server/src/main/bin/start.sh
Fix #515.
Change the config path to match the outputDirectory config in the assembly package file
No
No
No
=> [Bugfix] Fix start.sh with config path

paimon-web-server/src/main/bin/env.sh, paimon-web-server/src/main/bin/start.sh
… cdc
fix bug that "FLINK_HOME is null or ACTION_JAR_PATH is null"  when use cdc.
i had add FLINK_HOME  and ACTION_JAR_PATH in bin/env.sh, but it also throw error .
=> [Bugfix] Fix getting system environment variables error

tools/releasing/create_release_package.sh
`create_source_release.sh` does not support binary releasing, which could not run with quick start. Binary releasing of Paimon WebUI should be supported for releasing package of Paimon WebUI.
No.
No.
No.
=> [Release] Support binary releasing of Paimon WebUI
